version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=fixit
      - MARIADB_DATABASE=fixit
      - MARIADB_PASSWORD=fix_it
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8090:80'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'
    environment:
      - PMA_HOST=mariadb

  web:
    build:
      context: .
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/fixit?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: fixit
      SPRING_DATASOURCE_PASSWORD: fix_it
volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
    # privileged: true # Privileged mode could be required to run this container under Windows
