# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Push master branch to remote server

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up application properties
      run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=vokrobodo/fixit:prod
      
    - name: Push Docker image
      run: docker push vokrobodo/fixit:prod

    - name: Deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          docker stop fixit-prod || true
          docker rm fixit-prod || true
          docker pull vokrobodo/fixit:prod
          docker run -d --name fixit-prod -p 8080:8080 vokrobodo/fixit:prod
